// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeStorage } from '@/lib/safeStorage';

// VITE_SUPABASE_* are injected at build time from wrangler.toml [vars]
// The publishable key is safe to be in frontend code — it's designed to be public.
// Security is enforced by Supabase Row Level Security (RLS) policies, not by hiding this key.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? 'https://arhsjfguddgoqnsxydzc.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? 'sb_publishable_y5FG3pMb3Eg5EiDpq8SVfQ_q6US8yvE';

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? safeStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        'x-application-name': 'whycreatives',
      },
    },
  }
);